apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-autogen-team
  labels:
    app: fastapi-autogen-team
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-autogen-team
  template:
    metadata:
      labels:
        app: fastapi-autogen-team
    spec:
      containers:
        - name: fastapi-autogen-team
          image: lgcorzo/fastapi-autogen-team:v1.1.0
          ports:
            - containerPort: 4100
          envFrom:
            - secretRef:
                name: fastapi-autogen-secrets
          env:
            - name: DEFAULT_OTEL_ENDPOINT
              value: "http://opentelemetry-collector.monitoring.svc.cluster.local:4318/v1"
            - name: DEFAULT_HOST
              value: "0.0.0.0"
            - name: JIRA_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: fastapi-autogen-secrets
                  key: JIRA_API_TOKEN
            - name: JIRA_CLOUD
              valueFrom:
                secretKeyRef:
                  name: fastapi-autogen-secrets
                  key: JIRA_CLOUD
            - name: JIRA_INSTANCE_URL
              valueFrom:
                secretKeyRef:
                  name: fastapi-autogen-secrets
                  key: JIRA_INSTANCE_URL
            - name: JIRA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: fastapi-autogen-secrets
                  key: JIRA_USERNAME
            - name: R2R_PWD
              valueFrom:
                secretKeyRef:
                  name: fastapi-autogen-secrets
                  key: R2R_PWD
            - name: R2R_URL
              valueFrom:
                secretKeyRef:
                  name: fastapi-autogen-secrets
                  key: R2R_URL
            - name: R2R_USER
              valueFrom:
                secretKeyRef:
                  name: fastapi-autogen-secrets
                  key: R2R_USER
