name: Sync Docs to Wiki

on:
  push:
    paths:
      - 'documentation/**'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Sync docs to wiki
        uses: devops-infra/github-docs-to-wiki@v1.5.0
        with:
          path: docs
          token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "Sync docs to wiki"
