name: Sync Docs to Wiki

on:
  push:
    paths:
      - 'documentation/**'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4


      - name: github-docs-to-wiki
        uses: cmbrose/github-docs-to-wiki@v0.20
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          rootDocsFolder: documentation
          convertRootReadmeToHomePage: true
